### PR TITLE
Fix duplicate stack trace at error.str field

### LINKED ISSUE #7: concatenate stack and string only on tostring call
Typically stack size may be ~4 kB or more

It's too expensive when you send error message via network

Now we send stack trace twice (https://github.com/tarantool/errors/blob/master/errors.lua#L94)

Let's concatenate "str" and "stack" only on tostring call

### PR DESCRIPTION
**Pull request by HustonMmmavr**
Now error.str field contains only error message and method error.tostring()
concatenates error message and stack trace.

Closes #7

### CODE REVIEW

File: errors.lua [hunk 1]
```diff
@@ -91,11 +91,11 @@ function error_class:new(...)
 
     if self.capture_stack then
         stack = string.strip(debug.traceback("", level))
-        str = str .. '\n' .. stack
+        str = str
```
Comment (olegrok) [inline errors.lua]: I think expression `str = str` doesn't have any sense

File: errors.lua [hunk 2]
```diff
@@ -91,11 +91,11 @@ function error_class:new(...)
...
     end
 
     if self.log_on_creation then
-        log.error(str)
+        log.error(string.format("%s\n%s", str, stack))
```
Comment (rosik) [inline errors.lua]: do this right before `return e` by saying `log.error('%s', e)`

File: errors.lua [hunk 3]
```diff
@@ -296,7 +296,7 @@ local function wrap_with_suffix(suffix_format, ...)
                     stack_suffix = string.format(unpack(suffix_format))
                 end
 
-                obj.str = obj.str .. '\n' .. stack_suffix .. '\n' .. stack
+                obj.str = obj.str
```
Comment (rosik) [inline errors.lua]: This one is unnecessary too

File: errors.lua [hunk 4]
```diff
@@ -191,7 +191,7 @@ end
 -- @function tostring
 -- @treturn string
 function error_class.tostring(err)
-    return err.str
+    return string.format('%s\n%s', err.str, err.stack or '')
```
Comment (rosik) [inline errors.lua]:
```suggestion
local ret = err.str
if err.stack ~= nil then
    ret = ret .. '\n' .. err.stack
end

return ret
```

File: test/test_class.lua [hunk 5]
```diff
@@ -12,8 +12,11 @@ test:plan(7)
 
 local e_nostack = errors.new_class('No-stack error', {capture_stack = false})
 local err = e_nostack:new()
-test:is(err.stack, nil, 'capture_stack = false')
-
+test:test('capture_stack = false', function(subtest)
+    subtest:plan(2)
+    subtest:is(err.stack, nil, 'check stack is nil')
+    subtest:is(err:tostring(), 'No-stack error: \n', "check tostring() doesn't contains stacktrace")
```
Comment (rosik) [inline test/test_class.lua]:
```suggestion
    subtest:is(err:tostring(), 'No-stack error: ', "check tostring() doesn't contains stacktrace")
```
